### ISSUE TITLE
Getting this error with vpp mainline

### ISSUE THREAD

**Issue by Shaligram** [PANTHEONtech/vpptop#5]
# sudo -E /root/go/bin/vpptop
2019/06/24 11:14:51 Error occured while connecting: compatibility check failed: unknown message: "sw_interface_dump_63f5e3b7"

vpp# show interface
              Name               Idx    State  MTU (L3/IP4/IP6/MPLS)     Counter          Count
local0                            0     down          0/0/0/0

**Comment by ondrej-fabry** [comment]
Please ensure you are running `VPP 19.04.1`. The VPP from master (19.08-rc0) is not yet supported.

**Comment by ironpillow** [comment]
Hi,
I am also receiving the same error:

`2019/07/29 18:36:53 error occured while connecting: compatibility check failed: unknown message: "sw_interface_dump_052753c5"`

vpp# sh version
vpp v19.04.1-release built by root on e02854f54bd1 at Fri May 31 15:14:15 UTC 2019

**Comment by rastislavs** [comment]
For VPP 19.04, use the `vpp1904 ` branch: https://github.com/PantheonTechnologies/vpptop/tree/vpp1904

**Comment by ironpillow** [comment]
Thank you @rastislavszabo ! It worked.
